# -*- coding: utf-8 -*-
"""Restaurant_Sales_EDA_and_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XY1coIX-1ADw-uJbKoFfUy0jQyTr53L-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df1=pd.read_csv('/content/i1.csv')
df2=pd.read_csv('/content/i2.csv')

df=df1.merge(df2,how='outer')

df.shape

df.head(10)

df.tail(10)

df.info()

df.describe()

df.isnull().sum()

df=df.drop(['Table No.','Server Name','Covers','Variation','HSN'],axis=1)

df.shape

a=df['Final Total'].sum()
print(a)

df['Invoice No.'].unique()

b=df['Invoice No.'].nunique()

aov=a/b

aov

df.groupby('Item Name')['Qty.'].sum()

df.groupby('Item Name')['Qty.'].sum().sort_values(ascending=False)

e=df.groupby('Item Name')['Qty.'].sum().sort_values(ascending=False)[0:5]

sns.barplot(e)

e.plot(kind='bar')

e=df.groupby('Item Name')['Final Total'].sum().sort_values(ascending=False)[0:10]

e.plot(kind='bar')

df.groupby('Date')['Final Total'].sum()

df[df['Date']=='2023-09-15']['Final Total'].sum()

df.groupby('Date')['Final Total'].sum().loc['2023-09-15']

df[(df['Date']=='2023-09-15')&(df['Item Name']=='Chicken Noodles')]['Qty.'].sum()

df.groupby('Invoice No.').sum()
df['Final Total']>2000

df[df['Final Total']>2000]['Invoice No.']

j=df.groupby('Invoice No.')['Final Total'].sum()
j[j>2000]

j=df.groupby('Invoice No.')['Final Total'].sum()
j[j==2887.50]

df[df['Final Total']==2887.50]['Invoice No.']

df=df[df['Invoice No.']==28145]
df[['Final Total','Item Name','Qty.']].sum()

from wordcloud import WordCloud

text =' '.join(df['Item Name'].dropna().astype(str).values)

wordcloud = WordCloud(background_color='white',width=800,height=400).generate(text)
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud,interpolation='bilinear')
ax.set_title('word cloud of item Column')
plt.show()

from wordcloud import WordCloud

text =' '.join(df['Item Name'].dropna().astype(str).values)

wordcloud = WordCloud(background_color='white',width=800,height=400).generate(text)
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud,interpolation='NEAREST')
ax.set_title('word cloud of item Column')
plt.show()

from wordcloud import WordCloud

text =' '.join(df['Item Name'].dropna().astype(str).values)

wordcloud = WordCloud(background_color='white',width=800,height=400).generate(text)
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud,interpolation='BICUBIC')
ax.set_title('word cloud of item Column')
plt.show()

from wordcloud import WordCloud

text =' '.join(df['Item Name'].dropna().astype(str).values)

wordcloud = WordCloud(background_color='white',width=800,height=400).generate(text)
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud,interpolation='antialiased')
ax.set_title('word cloud of item Column')
plt.show()

from wordcloud import WordCloud

text =' '.join(df['Item Name'].dropna().astype(str).values)

wordcloud = WordCloud(background_color='white',width=800,height=400).generate(text)
fig, ax = plt.subplots(figsize=(10,6))
ax.imshow(wordcloud,interpolation='spline36')
ax.set_title('word cloud of item Column')
plt.show()